version: "3.9"

services:
  dynamodb:
    image: amazon/dynamodb-local
    container_name: dynamodb-local
    ports:
      - "8000:8000"

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: book-lending-api
    environment:
      # Your Program.cs/DynamoDb client should read this if present
      DDB_SERVICE_URL: http://dynamodb:8000
      ASPNETCORE_URLS: http://0.0.0.0:8080
    ports:
      - "8080:8080"
    depends_on:
      - dynamodb
